export const subjects=[
    "Mathematics",
    "Heigher Mathematics",
    "Physics",
    "Chemistry",
    "Biology",
    "English",
    "Bangla",
    "Accounting",
    "Economics",
    "History",
    "Geography",
    "Computer Science",
    "ICT",
    "C/C++ Programming",
    "Java",
    "Web Development",
     "Python",
     "IELTS",
    "TOEFL",
    "GRE",
]
export const classes=[
    "One",
    "Two",
    "Three",
    "Four",
    "Five",
    "Six",
    "Seven",
    "Eight",
    "SSC",
    "HSC",
    "University Admission",
    "Medical Admission",
    "Engineering Admission",
    "others",
    "Cadet College Admission"
]